### PR TITLE
Added Logo To Twitch User

### PR DESCRIPTION
**Pull request by luxiconn**
I added a logo property to the TwitchUser class because I need it for a project.

### CODE REVIEW

**Comment by tpavlek** [comment]
Just a couple quick things since I'm on phone and can't check:

Is logo always provided via the API? What if a user hasn't set one, does twitch just use a default? If not, make sure to add an isset check so that everything doesn't break.

Is the logo returned as a URL to an image file on their server or a base64 encoded image or what? Add that to the docblock of getPhoto so people know.

As soon as you address those couple things I'll be glad to merge :)

**Comment by luxiconn** [comment]
1) Logo is always provided by the API, I will do some research and see what it returns if the user hasn't set one but there will always be a logo field in the response.

2) The logo is returned as a URL to the image file on their CDN, it looks like this http://static-cdn.jtvnw.net/jtv_user_pictures/nicks451-profile_image-65d418dd59842623-300x300.png. I'll make the update later today.

Thanks

**Comment by luxiconn** [comment]
I updated the docblock for getPhoto to be more descriptive on what the expected result should be.

**Comment by tpavlek** [comment]
Released this feature in 1.2.1.

Thanks for the contribution!

**Pull request merged**
